// Notification
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";
export const FADE_MESSAGE = "FADE_MESSAGE";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const SHOW_TOAST = "SHOW_TOAST";

// Check credentials
export const CHECK_CREDS = "CHECK_CREDS";
// Signin
export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const SIGNIN_REQUEST_SUCCESS = "SIGNIN_REQUEST_SUCCESS";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILURE = "SIGNIN_FAILURE";
export const SIGNIN_REQUEST_FAILURE = "SIGNIN_REQUEST_FAILURE";
export const SIGNIN_REQUIRED = "SIGNIN_REQUIRED";
// Login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_REQUEST_FAILURE = "LOGIN_REQUEST_FAILURE";
export const LOGIN_REQUIRED = "LOGIN_REQUIRED";
// Log out
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// Game - Responses
export const PLAYERSELS_REQUEST_SUCCESS = "PLAYERSELS_REQUEST_SUCCESS";
export const PLAYERSEL_REQUEST_FAILURE = "PLAYERSEL_REQUEST_FAILURE";
export const PLYRMV_REQUEST_SUCCESS = "PLYRMV_REQUEST_SUCCESS";
export const PLYRMV_REQUEST_FAILURE = "PLYRMV_REQUEST_FAILURE";
export const CMPTRMV_REQUEST_SUCCESS = "CMPTRMV_REQUEST_SUCCESS";
export const CMPTRMV_REQUEST_FAILURE = "CMPTRMV_REQUEST_FAILURE";
export const GMBRD_REQUEST_SUCCESS = "GMBRD_REQUEST_SUCCESS";

export const GMBRD_REQUEST_FAILURE = "GMBRD_REQUEST_FAILURE";
export const INITGM_REQUEST_SUCCESS = "INITGM_REQUEST_SUCCESS";
export const INITGM_REQUEST_FAILURE = "INITGM_REQUEST_FAILURE";

/// GAME - CRUD Requests
export const INIT_NEW_GM = "INIT_NEW_GM";
export const GM_OVER = "GM_OVER";
export const SET_MD = "SET_MD";
export const READ_INITGM_REQUEST = "READ_INITGM_REQUEST";
export const READ_PLAYERSELS_REQUEST = "READ_PLAYERSELS_REQUEST";
export const READ_CMPTRMV_REQUEST = "READ_CMPTRMV_REQUEST";
export const READ_PLYRMV_REQUEST = "READ_PLYRMV_REQUEST";
export const READ_GMBRD_REQUEST = "READ_GMBRD_REQUEST";
export const GM_BTN_CHNG = "GM_BTN_CHNG";
export const NEW_GM = "NEW_GM";
export const RESET_GM = "RESET_GM";
export const UPD_GMBRD = "UPD_GMBRD";
export const SEL_CHNG = "SEL_CHNG";
export const PLAY_GM = "PLAY_GM";
export const STOP_GM = "STOP_GM";
export const OPEN_MDL = "OPEN_MDL";
export const LTR_DRPD = "LTR_DRPD";
export const START_CLOCK = "START_CLOCK";
export const PAUSE_CLOCK = "PAUSE_CLOCK";
export const PLAY_MODE = "PLAY_MODE";
export const INCR_PLYR = "INCR_PLYR";
export const TIME_UP = "TIME_UP";
